--- #YAML:1.0
name:               Class-Data-Inheritable-Translucent
version:            1.01
abstract:           Inheritable, overridable, translucent class data / object attributes
author:
    - Ryan McGuigan, Steve Hay (shay@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
